baseURL = 'https://madcap.cc/'
defaultContentLanguage = 'fr'
disableKinds = ["taxonomy", "term", "rss"]
enableEmoji = true
enableRobotsTXT = true
languageCode = 'fr-FR'
sectionPagesMenu = 'main'
title = 'MadCap'

[markup.goldmark.parser.attribute]
block = true
title = true
[markup.goldmark.renderer]
unsafe = true

[params]
homepage = '/accueil'

[languages]
[languages.fr]
languageCode = 'fr-FR'
languageName = 'Français'
weight = 1
[[languages.fr.menus.main]]
name = 'Accueil'
pageRef = '/'
weight = 1
[[languages.fr.menus.main]]
name = 'Organisateurs'
pageRef = '/orga/'
weight = 2
[[languages.fr.menus.main]]
name = 'Contact'
pageRef = '/contact/'
weight = 3
[[languages.fr.menus.main]]
name = 'Participant'
pageRef = '/participant/'
weight = 4

[languages.en]
languageCode = 'en-GB'
languageName = 'English'
[languages.en.menus]
[[languages.en.menus.main]]
name = 'Home'
pageRef = '/'
weight = 1
[[languages.en.menus.main]]
name = 'Organizers'
pageRef = '/orga/'
weight = 2
[[languages.en.menus.main]]
name = 'Contact'
pageRef = '/contact/'
weight = 3
[[languages.en.menus.main]]
name = 'Participant'
pageRef = '/participant/'
weight = 4
